apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    control-plane: kubeflow
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    control-plane: kubeflow
