apiVersion: v1
kind: ConfigMap
metadata:
  name: model_config
data:
  model_config.yaml: |-
    model_config_list {
      config {
        name: "test_model"
        base_path: "/mnt/uthermai/"
        model_platform: "tensorflow"
        model_version_policy{
          specific {
            versions: 1
          }
        }   
     }
  }
