version: '3'
services:
  redis:
    image: bitnami/redis:4.0.14
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: admin
    ports:
      - "6379:6379"

  myapp:
    image: ai.tencentmusic.com/tme-public/kubeflow-dashboard:tme-2021.10.01.7
    restart: unless-stopped
    command: ['bash','-c','sleep 10000000 && /entrypoint.sh']   # 生产模式
    environment:
      STAGE: 'dev'
      REDIS_HOST: 'host.docker.internal'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: admin
      HOST: 127.0.0.1
      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
      ENVIRONMENT: DEV
      GPU_TYPE: NVIDIA

    ports:
      - "80:80"
    depends_on:
      - redis
    volumes:
      - ../../myapp/:/home/myapp/myapp/
      - ./file:/pvc
      - ./entrypoint.sh:/entrypoint.sh
      - ./config.py:/home/myapp/myapp/config.py
      - ./kubeconfig:/home/myapp/kubeconfig
#      - /Users/pengluan/data-master/kubeflow/src/pipelines/sdk/python/:/kubeflow/src/pipelines/sdk/python/
#      - /Users/pengluan/data-master/kubeflow/src/fairing/:/kubeflow/src/fairing/
#      - /Users/pengluan/data-master/kubeflow/src/xgboost-operator/sdk/python/:/kubeflow/src/xgboost-operator/sdk/python/
#      - /Users/pengluan/data-master/kubeflow/src/kfserving/python/kfserving/:/kubeflow/src/kfserving/python/kfserving/
#      - /Users/pengluan/data-master/kubeflow/src/tf-operator/sdk/python/:/kubeflow/src/tf-operator/sdk/python/
#      - /Users/pengluan/data-master/kubeflow/src/katib/sdk/python/v1alpha3/:/kubeflow/src/katib/sdk/python/v1alpha3/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/:/usr/local/lib/python3.6/dist-packages/flask/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_appbuilder/:/usr/local/lib/python3.6/dist-packages/flask_appbuilder/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/:/usr/local/lib/python3.6/dist-packages/sqlalchemy/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wtforms/:/usr/local/lib/python3.6/dist-packages/wtforms/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_wtf/:/usr/local/lib/python3.6/dist-packages/flask_wtf/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kubernetes/:/usr/local/lib/python3.6/dist-packages/kubernetes/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marshmallow_sqlalchemy/:/usr/local/lib/python3.6/dist-packages/marshmallow_sqlalchemy/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marshmallow/:/usr/local/lib/python3.6/dist-packages/marshmallow/
#      - /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marshmallow_enum/:/usr/local/lib/python3.6/dist-packages/marshmallow_enum/



#
#  beat:
#    image: ai.tencentmusic.com/tme-public/kubeflow-dashboard:tme-2021.10.01.7
#    restart: "no"
#    command: ["bash","-c","sleep 100000000 && celery beat --app=myapp.tasks.celery_app:celery_app --loglevel=info"]
#    shm_size: '100gb'
#    environment:
#      REDIS_HOST: 'host.docker.internal'
#      REDIS_PORT: '6379'
#      REDIS_PASSWORD: admin
#      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
#      ENVIRONMENT: DEV
#    depends_on:
#      - redis
#    volumes:
#      - ../../myapp/:/home/myapp/myapp/
#      - ./file:/pvc
#      - ./entrypoint.sh:/entrypoint.sh
#      - ./config.py:/home/myapp/myapp/config.py
#      - ./kubeconfig:/home/myapp/kubeconfig
##
#
##
#
#  worker:
#    image: ai.tencentmusic.com/tme-public/kubeflow-dashboard:tme-2021.10.01.7
#    restart: unless-stopped
#    command: ["bash","-c","sleep 100000000 && celery worker --app=myapp.tasks.celery_app:celery_app --loglevel=info --pool=prefork -Ofair -c 40"]
#    environment:
#      REDIS_HOST: 'host.docker.internal'
#      REDIS_PORT: '6379'
#      REDIS_PASSWORD: admin
#      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
#      ENVIRONMENT: DEV
#    depends_on:
#      - redis
#    volumes:
#      - ../../myapp/:/home/myapp/myapp/
#      - ./file:/pvc
#      - ./entrypoint.sh:/entrypoint.sh
#      - ./config.py:/home/myapp/myapp/config.py
#      - ./kubeconfig:/home/myapp/kubeconfig



