apiVersion: v1
data:
  alertmanager.yaml: Cmdsb2JhbDoKICByZXNvbHZlX3RpbWVvdXQ6IDVtCnRlbXBsYXRlczoKLSAnL2V0Yy9hbGVydG1hbmFnZXIvdGVtcGxhdGUvKi50bXBsJwpyb3V0ZToKICBncm91cF9ieTogWydhbGVydG5hbWUnLCAnY2x1c3RlcicsICdzZXJ2aWNlJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDFoCiAgcmVjZWl2ZXI6ICdudWxsJwogIHJvdXRlczoKICAtIG1hdGNoX3JlOgogICAgICBuYW1lc3BhY2U6ICIuKiIKICAgIHJlY2VpdmVyOiAncGVuZ2x1YW4nCgojIOWRiuitpuaKkeWItuOAgumBv+WFjemHjeWkjeWRiuitpueahOOAggojIGh0dHBzOi8veXVubHpoZW5nLmdpdGJvb2suaW8vcHJvbWV0aGV1cy1ib29rL3BhcnRpLXByb21ldGhldXMtamktY2h1L2FsZXJ0L2FsZXJ0LW1hbmFnZXItaW5oaWJpdAppbmhpYml0X3J1bGVzOgotIHNvdXJjZV9tYXRjaDoKICAgIHNldmVyaXR5OiAnY3JpdGljYWwnCiAgdGFyZ2V0X21hdGNoOgogICAgc2V2ZXJpdHk6ICd3YXJuaW5nJwogICMgQXBwbHkgaW5oaWJpdGlvbiBpZiB0aGUgYWxlcnRuYW1lIGlzIHRoZSBzYW1lLgogIGVxdWFsOiBbJ2FsZXJ0bmFtZScsICdjbHVzdGVyJywgJ3NlcnZpY2UnXQpyZWNlaXZlcnM6CgotIG5hbWU6ICdwZW5nbHVhbicKICB3ZWJob29rX2NvbmZpZ3M6CiAgLSBzZW5kX3Jlc29sdmVkOiB0cnVlCiAgICB1cmw6ICdodHRwOi8vc3dhbGxvdy5tdXNpYy53b2EuY29tL2RpL2FwaS1jZW50ZXIvcHVzaD9rZXk9cGFudGhlci1hbGVydG1hbmFnZXInCgotIG5hbWU6ICdudWxsJwo=
  
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
