apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Control pane
#  - ../../admission-webhook/webhook/v3
  - ../../kubeflow-roles/base
#  - ../../profiles/base_v3
  # Training Operators
  - ../../pytorch-job/pytorch-job-crds/overlays/application
  - ../../pytorch-job/pytorch-operator/overlays/application
  - ../../tf-training/tf-job-crds/overlays/application
  - ../../tf-training/tf-job-operator/overlays/application
  - ../../mxnet-job/mxnet-operator/overlays/application
#  - ../../mpi-job/mpi-operator/overlays/application

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - ./config/params.env
  name: kubeflow-config
vars:
# We need to define vars at the top level otherwise we will get
# conflicts.
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config

